services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    # The following environment variables can be set in a .env file.
    # If not set, defaults are used for local development (minioadmin/minioadmin).
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - ./minio-data:/data
